### ISSUE TITLE
[Security] Workflow deploy-prod.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by igibek** [navikt/pam-internal-search-api#6]
The workflow deploy-prod.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by V1adau** [comment]
Thanks for taking the time to report the issue, sorry it took 2 and a half years for anyone to respond. This was fixed in 485625184a9149511659d6efc18318733f8be42a when moving to [pam-deploy](https://github.com/navikt/pam-deploy) for deploy-workflow.
